# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 883dd4d8193d8483b4a23732e7ddfe071640b1421f7aa0032885aa61dc5a98b09c29c61c850d9802580c96c17a83a381cd5ec38c858380a8624ae3d6a634f7a4

test:
  secret_key_base: e73c88e9982c03d8347fba81295514fbb9fb20c597d351d485e468c44ed56ccb3b409dc6a866f6bde969d85f5ee300d175ad6fdf59d1e4c9d231b763fbdf989f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
